version: '3'
services:
  artemis:
    container_name: activeMQ
    image: vromero/activemq-artemis
    restart: always
    environment:
      - ARTEMIS_USERNAME=emin
      - ARTEMIS_PASSWORD=eminemin
    ports:
      - "8161:8161"
      - "61616:61616"